sonata_admin:
    title: 'Admin'
    title_logo: '/images/logo-rezouani.jpg'
    show_mosaic_button: false

      #options:
    #html5_validate: false

    assets:
        extra_stylesheets:
            - css/admin.css
        extra_javascripts:
            - js/admin.js

    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

        groups:
            admins:
                label: 'Admins'
                icon: '<i class="fa fa-magic"></i>'
                keep_open: true

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]