#index:
#    path: /
#    controller: App\Controller\DefaultController::index

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /de
        permanent: true

app:
    path: /{_locale}
    defaults:
        _controller: 'App\Controller\IndexController::index'
    requirements:
        _locale: "%supported_languages%"

fos_user:
    prefix: /{_locale}
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"